version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  quote_api:
    build: ./quote_api
    volumes:
      - ./quote_api:/usr/src/app
    ports:
      - 5001:5001
    depends_on:
      - db
    stdin_open: true
    tty: true

networks:
  postgres:
    driver: bridge
